# Generated by Django 6.0.6 on 2026-06-26 21:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user_profiles.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "private"), ("public", "public")],
                        default=user_profiles.models.ProfileVisibility[
                            "PRIVATE"
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("eng", "eng")],
                        default=user_profiles.models.Lang["ENG"],
                        max_length=3,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("dark", "dark"), ("light", "light")],
                        default=user_profiles.models.Theme["LIGHT"],
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("visibility__in", ["private", "public"])
                        ),
                        name="visibility_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("language__in", ["eng"])),
                        name="language_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("theme__in", ["dark", "light"])),
                        name="theme_valid",
                    ),
                ],
            },
        ),
    ]
