# Generated by Django 6.0.6 on 2026-07-11 20:34

import uuid

import django.db.models.deletion
from django.db import migrations, models

import cards.models
import shared.constraints


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("basic", "basic"), ("reverse", "reverse")],
                        default=cards.models.CardKind["BASIC"],
                        max_length=16,
                    ),
                ),
                ("front", models.CharField(max_length=50)),
                ("back", models.CharField(max_length=50)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="decks.deck",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["basic", "reverse"])),
                        name=shared.constraints.ConstraintName[
                            "CARD_KIND_VALID"
                        ],
                    )
                ],
            },
        ),
    ]
