# Generated by Django 6.0.6 on 2026-06-22 14:11

import uuid

from django.db import migrations, models

import shared.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[shared.validators.user_username_validator],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("username__contains", "@"), _negated=True),
                        name="users_user_username_no_at_sign",
                    )
                ],
            },
        ),
    ]
