# Generated by Django 6.0.6 on 2026-07-05 15:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shared.constraints
import shared.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=25)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "private"), ("public", "public")],
                        default=shared.models.Visibility["PRIVATE"],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("visibility__in", ["private", "public"])
                        ),
                        name=shared.constraints.ConstraintName[
                            "DECK_VISIBILITY_VALID"
                        ],
                    )
                ],
            },
        ),
    ]
