# Defining a group of backend servers to forward requests to.
# You can add multiple servers and Nginx distributes traffic
# between them automatically (load balancing).
upstream django {
    server web:8000;
    # You can also set weights for each server:
    # server web1:8000 weight=3;  # gets 3x more traffic
    # server web2:8000 weight=1; 
}

# To configure an HTTPS server, the ssl parameter must be enabled on
# listening sockets in the server block, and the locations of the
# server certificate and private key files should be specified:

# server {
#     listen              443 ssl;
#     server_name         www.example.com;
#     ssl_certificate     www.example.com.crt;
#     ssl_certificate_key www.example.com.key;
#     ssl_protocols       TLSv1.2 TLSv1.3;
#     ssl_ciphers         HIGH:!aNULL:!MD5;
#     ...
# }
# https://nginx.org/en/docs/http/configuring_https_servers.html

server {
    # HTTP port. Add 
    listen 80;
    # Change to your domain for production.
    server_name yourdomain.com www.yourdomain.com;
    
    # Any request to yourdomain.com/static/ gets served
    # directly from the staticfiles/
    location /static/ {
        alias /src/staticfiles/;
    }

    # Forward any other request to Gunicorn.
    location / {
        # Upstream alias defined above.
        proxy_pass http://django;
        
        # Passes the original domain to Django.
        # Without this Django sees web:8000 instead
        # of yourdomain.com.
        proxy_set_header Host $host;

        # Passes the real user IP to Django. Without this
        # every request appears to come from Nginx's IP.
        proxy_set_header X-Real-IP $remote_addr;
        
        # Maintains the full chain of IPs if there are
        # multiple proxies in front of Nginx.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Tells Django whether the request was HTTP or HTTPS.
        # Django needs this behind a proxy to correctly handle
        # SECURE_SSL_REDIRECT and generate correct URLs.
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
